name: hostel_management
description: "A Hostel Management Flutter Application."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8

  # Database
  sqflite: ^2.3.3
  path: ^1.9.0
  path_provider: ^2.1.2

  # Communication (SMS, Email, Calls, Browser links)
  url_launcher: ^6.3.0

  # State management (optional, good practice for bigger projects)
  provider: ^6.1.2

  # For nice UI components (optional)
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
